[package]
name = "hand2midi"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
leaprs = { version = "*", default-features = false }
midir = "0.9.1"
mouse-rs = "0.4.2"
